entervalue: dialog {label = "Ñמחהאםטו עטןמגמי הועאכט"; 
   : spacer{height=1;}
   
   : text {label = "Âגוהטעו נאחלונû:"; key = "t1";}  // עוךסעמגמו ןמכו
   
   : edit_box {label = "A1  לל:"; key = "key_A1"; edit_width=10; value = "";}
   : edit_box {label = "A2  לל:"; key = "key_A2"; edit_width=10; value = "";} 
   : edit_box {label = "A3  לל:"; key = "key_A3"; edit_width=10; value = "";} 
   : edit_box {label = "B1  לל:"; key = "key_B1"; edit_width=10; value = "";}
   : edit_box {label = "B2  לל:"; key = "key_B2"; edit_width=10; value = "";}
   : edit_box {label = "B3  לל:"; key = "key_B3"; edit_width=10; value = "";}
   : edit_box {label = "C1  לל:"; key = "key_C1"; edit_width=10; value = "";}
   : edit_box {label = "D1  לל:"; key = "key_D1"; edit_width=10; value = "";}
   : edit_box {label = "R1  לל:"; key = "key_R1"; edit_width=10; value = "";}
   : edit_box {label = "R2  לל:"; key = "key_R2"; edit_width=10; value = "";}
   : edit_box {label = "R3  לל:"; key = "key_R3"; edit_width=10; value = "";}
   : edit_box {label = "Di1  לל:"; key = "key_Di1"; edit_width=10; value = "";}
   : edit_box {label = "Di2  לל:"; key = "key_Di2"; edit_width=10; value = "";} 
   : spacer{height=1;}

   ok_cancel;
} 	